### ISSUE TITLE
[Bug][Fabric 1.19.2] Few issues

### ISSUE THREAD

**Issue by kingkuys2123** [gottsch/gottsch-minecraft-MageFlame#15]
MageFlame Fabric mc1.19.2-v1.2.0
Fabric 0.14.14
Fabric API 0.73.2
Java 8 Update 351

## Can break Flame Blocks
In survival mode, I can break **Greater Revelation Block**, **Mage Flame Block**, and **Lesser Revelation Block**
![image](https://user-images.githubusercontent.com/114457180/218891385-93a43623-0b75-4e0d-a207-2523df2a9977.png)

## Missing names
![image](https://user-images.githubusercontent.com/114457180/218891311-5caa7553-d2ee-4161-8e96-81573a1d15ea.png)

## Can't mine through the Flame Blocks
The Flame Blocks always gets in the way when I am trying to mine, I suggest these Flame Blocks should have the same properties as the [MineCraft's light blocks](https://minecraft.fandom.com/wiki/Light_Block)

**Comment by gottsch** [comment]
Should be fixed in v1.2.1

**Comment by kingkuys2123** [comment]
Sweet! thanks :)
